import type {JsonSchema} from "./types";

export const kitchenSinkSchema = {
  type: "object",
  title: "Project Intake",
  description: "Descriptions render above fields and every level is wrapped in a transparent surface.",
  required: ["projectName", "priority", "budget", "payment"],
  propertyOrdering: [
    "intro",
    "projectName",
    "summary",
    "contactEmail",
    "referenceUrl",
    "requiresReview",
    "priority",
    "audience",
    "status",
    "channels",
    "tools",
    "reviewTags",
    "budget",
    "launchDate",
    "launchTime",
    "approvalDeadline",
    "owner",
    "payment",
    "fulfillment",
    "mixedItems",
    "milestones",
  ],
  properties: {
    intro: {
      type: "null",
      title: "Scope",
      description: "This block is display-only and will not be present in data.",
    },
    projectName: {
      type: "string",
      title: "Project name",
      description: "Short unformatted strings render as single-line inputs by default.",
      minLength: 2,
      maxLength: 120,
    },
    summary: {
      type: "string",
      title: "Project summary",
      description: "Long unformatted strings render as multiline text areas.",
      maxLength: 512,
    },
    contactEmail: {
      type: "string",
      title: "Contact email",
      description: "Email format strings render as email inputs.",
      format: "email",
    },
    referenceUrl: {
      type: "string",
      title: "Reference URL",
      description: "URI format strings render as URL inputs.",
      format: "uri",
    },
    requiresReview: {
      type: "boolean",
      title: "Requires review",
      description: "Boolean fields render with HeroUI switch controls.",
    },
    priority: {
      type: "integer",
      title: "Priority",
      description: "Integer values with minimum and maximum render as a horizontal slider.",
      minimum: 1,
      maximum: 5,
    },
    audience: {
      type: "string",
      title: "Audience",
      description: "Fewer than six enum options render as radio buttons.",
      enum: ["Internal", "Customer", "Partner"],
    },
    status: {
      type: "string",
      title: "Status",
      description: "Six enum options render as a dropdown.",
      enum: ["Draft", "Review", "Approved", "Blocked", "Archived", "Paused"],
    },
    channels: {
      type: "array",
      title: "Channels",
      description: "Six or more enum string options render as a multiselect dropdown.",
      uniqueItems: true,
      items: {
        type: "string",
        title: "Channel",
        description: "A delivery channel for the project.",
        enum: ["Email", "Web", "Mobile", "Retail", "Partner", "Events"],
      },
    },
    tools: {
      type: "array",
      title: "Tools",
      description: "Fewer than six enum string options render as a checkbox group.",
      uniqueItems: true,
      items: {
        type: "string",
        title: "Tool",
        description: "A tool used by the project team.",
        enum: ["Figma", "GitHub", "Vercel"],
      },
    },
    reviewTags: {
      type: "array",
      title: "Review tags",
      description: "Unique enum string arrays keep one instance of each selected string.",
      uniqueItems: true,
      items: {
        type: "string",
        title: "Review tag",
        description: "A unique review tag for filtering project feedback.",
        enum: ["Accessibility", "Performance", "Security", "Design", "Content", "Compliance"],
      },
    },
    budget: {
      type: "number",
      title: "Budget",
      description: "Number fields without both minimum and maximum render as HeroUI number fields.",
      minimum: 0,
    },
    launchDate: {
      type: "string",
      title: "Launch date",
      description: "Date strings render with HeroUI DatePicker.",
      format: "date",
    },
    launchTime: {
      type: "string",
      title: "Launch time",
      description: "Time strings render with HeroUI TimeField.",
      format: "time",
    },
    approvalDeadline: {
      type: "string",
      title: "Approval deadline",
      description: "Date-time strings render with HeroUI DatePicker minute granularity.",
      format: "date-time",
    },
    owner: {
      type: "object",
      title: "Owner",
      description: "Nested objects render inside their own transparent surface.",
      required: ["name"],
      propertyOrdering: ["name", "email", "website", "notes"],
      properties: {
        name: {
          type: "string",
          title: "Owner name",
          description: "Nested short strings render as full-width single-line inputs.",
          maxLength: 120,
        },
        email: {
          type: "string",
          title: "Owner email",
          description: "Nested email fields use the same formatted string layout.",
          format: "email",
        },
        website: {
          type: "string",
          title: "Owner website",
          description: "Nested URI fields use the same formatted string layout.",
          format: "uri",
        },
        notes: {
          type: "string",
          title: "Owner notes",
          description: "Empty strings are preserved only when minLength is explicitly zero.",
          minLength: 0,
          maxLength: 512,
        },
      },
    },
    payment: {
      title: "Payment method",
      description: "Branching uses a dropdown and anyOf is intentionally treated as oneOf in V1.",
      anyOf: [
        {
          type: "object",
          title: "Card",
          description: "Collect card payment details for this project.",
          required: ["cardNumber"],
          properties: {
            cardNumber: {
              type: "string",
              title: "Card number",
              description: "Card number is required when the card payment branch is selected.",
              maxLength: 19,
            },
          },
        },
        {
          type: "object",
          title: "Bank transfer",
          description: "Collect bank transfer details for this project.",
          required: ["iban"],
          properties: {
            iban: {
              type: "string",
              title: "IBAN",
              description: "IBAN is required when the bank transfer branch is selected.",
              maxLength: 34,
            },
          },
        },
      ],
    },
    fulfillment: {
      title: "Fulfillment path",
      description: "oneOf branches use the same dropdown selector layout as anyOf.",
      oneOf: [
        {
          type: "object",
          title: "Self serve",
          description: "Collect details for a self-serve fulfillment path.",
          required: ["portal"],
          properties: {
            portal: {
              type: "string",
              title: "Portal URL",
              description: "URI format strings render as URL inputs inside branch variants.",
              format: "uri",
            },
          },
        },
        {
          type: "object",
          title: "Assisted",
          description: "Collect details for an assisted fulfillment path.",
          required: ["manager"],
          properties: {
            manager: {
              type: "string",
              title: "Manager",
              description: "Short strings render as single-line inputs inside branch variants.",
              maxLength: 120,
            },
          },
        },
      ],
    },
    mixedItems: {
      type: "array",
      title: "Mixed items",
      description: "Array items can choose between object, enum string, null, and boolean oneOf variants.",
      maxItems: 4,
      items: {
        title: "Mixed item",
        description: "Each item selects one of four different schema shapes.",
        default: {label: ""},
        oneOf: [
          {
            type: "object",
            title: "Object",
            description: "Collects a labeled note for this item.",
            required: ["label"],
            properties: {
              label: {
                type: "string",
                title: "Label",
                description: "Short label for the object item.",
                maxLength: 80,
              },
              note: {
                type: "string",
                title: "Note",
                description: "Optional note for the object item.",
                maxLength: 160,
              },
            },
          },
          {
            type: "string",
            title: "Enum string",
            description: "Choose a named string value.",
            enum: ["Alpha", "Beta", "Gamma"],
          },
          {
            type: "null",
            title: "Null",
            description: "Represents an intentionally empty item.",
          },
          {
            type: "boolean",
            title: "Boolean",
            description: "Toggle a true or false item value.",
          },
        ],
      },
    },
    milestones: {
      type: "array",
      title: "Milestones",
      description: "Array fields render item controls and an add button until maxItems is reached.",
      maxItems: 3,
      items: {
        type: "object",
        title: "Milestone",
        description: "Each milestone is wrapped as a nested object level.",
        required: ["name"],
        properties: {
          name: {
            type: "string",
            title: "Name",
            description: "Short milestone names render as single-line inputs by default.",
            maxLength: 80,
          },
          due: {
            type: "string",
            title: "Due date",
            description: "Optional milestone due dates render with HeroUI DatePicker.",
            format: "date",
          },
        },
      },
    },
  },
} satisfies JsonSchema;

export const primitiveSchema = {
  type: "object",
  title: "Primitive fields",
  description: "A smaller schema showing primitive field rendering.",
  required: ["name", "email"],
  properties: {
    name: {
      type: "string",
      title: "Name",
      description: "Required short string rendered as a single-line text field.",
      minLength: 2,
    },
    email: {
      type: "string",
      title: "Email",
      description: "Email strings render as HeroUI text fields with email input semantics.",
      format: "email",
    },
    age: {
      type: "integer",
      title: "Age",
      description: "Integer values with minimum and maximum render as a horizontal slider.",
      minimum: 18,
      maximum: 80,
    },
    newsletter: {
      type: "boolean",
      title: "Subscribe to newsletter",
      description: "Boolean fields render with HeroUI switch controls.",
    },
  },
} satisfies JsonSchema;
